config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root "users#show"
  resources :conversations
  resources :comments
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :ratings
  #get "/ratings" => "ratings#index"
  #post "/ratings" => "ratings#create", :as => 'ratings'
  #resources :users, only: :show
  get "/:username" => "users#show"
  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: conversations
#
#  id                        :bigint           not null, primary key
#  comments_count            :integer          default(0)
#  status                    :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  comment_id                :integer
#  company_representative_id :bigint           not null
#  customer_id               :bigint           not null
#  rating_id                 :integer
#
# Indexes
#
#  index_conversations_on_company_representative_id  (company_representative_id)
#  index_conversations_on_customer_id                (customer_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_representative_id => users.id)
#  fk_rails_...  (customer_id => users.id)
#
class Conversation < ApplicationRecord
  belongs_to :company_representative, class_name: 'User', counter_cache: true
  belongs_to :customer, class_name: 'User', counter_cache: true
  has_many :comments
  has_many :ratings

  enum status: { open: "open", closed: "closed", urgent: "urgent" }
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  before_action :set_conversation, only: %i[show edit update destroy]

  # GET /conversations or /conversations.json
  def index
    redirect_back fallback_location: root_url, alert: "You're not authorized for that."
    @conversations = Conversation.all
  end

  # GET /conversations/1 or /conversations/1.json
  def show
    if current_user != @conversation.customer && current_user != @conversation.company_representative
      redirect_back fallback_location: root_url, alert: "You're not authorized for that."
    end
  end

  # GET /conversations/new some alterations here
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
    redirect_back fallback_location: root_url, alert: "You're not authorized for that."
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.save
    
    the_first_comment = @conversation.comments.create(
      body: "Hello, how can I help you today?",
      author_id: current_user.id
      )
  
    #conversation_params[:conversation][:comment_id] = the_first_comment.id
    
    @conversation.open!
    @conversation.comment_id = the_first_comment.id

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1 or /conversations/1.json
  def update
    
    if params['status'] != nil
      
      the_status = params['status']
      if the_status == 'open'
        @conversation.open!
      elsif the_status == 'closed'
        @conversation.close!
      else 
        @conversation.urgent!
      end

    end

    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1 or /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_conversation
    @conversation = Conversation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def conversation_params
    params.require(:conversation).permit(:company_representative_id, :customer_id, :comment_id, :status)
  end
end

app/helpers/conversations_helper.rb
# frozen_string_literal: true

module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :company_representative_id %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.select :customer_id, User.weave_username_and_id_into_array %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary btn-block" %>
  </div>
<% end %>

app/views/conversations/_rating_input_form.html.erb
<%= form_with(model: rating) do |form| %>

  <div class="field">
    <%= form.label :grade %>
    <%= form.select :grade, [0, 1, 2, 3, 4, 5] %>
  </div>

  <div class="field">
    <%= form.hidden_field :gradee_id%>
  </div>

  <div class="field">
    <%= form.hidden_field :grader_id%>
  </div>

  <div class="field">
    <%= form.hidden_field :conversation_id%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary btn-block" %>
  </div>
<% end %>

app/views/conversations/_status_change_form.html.erb
<%= form_with(model: conversation) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ["open", "closed", "urgent"] %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary btn-block" %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<table>
  <thead>
    <tr>
      <th>Company representative</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.company_representative_id %></td>
        <td><%= conversation.customer_id %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<%= turbo_stream_from @conversation %>

<h1>
  Conversation <%= @conversation.id %>
</h1>

<p class="mt-4">
  <strong>Company representative:</strong>
  <%= User.find(@conversation.company_representative_id).username.capitalize() %>
</p>

<% if @conversation.closed? %>
  <p>
    <strong> Company Representative Rating:</strong>
    <% if @conversation.ratings.where( {gradee_id: @conversation.company_representative_id} ).count != 0 %>
      <div class="row mb-6">
        <div class="col-md-6 mb-4">
          <%= render "/shared/rate_bar", number: @conversation.ratings.where( {gradee_id: @conversation.company_representative_id} ).first.grade %>
        </div>
      </div> 
    <% else %>
      <div class="col-md-3 mb-4">
        <% if current_user.customer?  %>
          <%= render "/conversations/rating_input_form", rating: Rating.new(gradee_id: @conversation.company_representative_id, grader_id: @conversation.customer_id, conversation_id: @conversation.id) %>
        <% end %>
      </div>
    <% end %>
  </p>
<% end %>


<p>
  <strong>Customer:</strong>
  <%= User.find(@conversation.customer_id).username.capitalize() %>
</p>

<% if @conversation.closed? %>
  <p>
    <strong> Customer Rating:</strong>
    <% if @conversation.ratings.where( {gradee_id: @conversation.customer_id} ).count != 0 %>
      <div class="row mb-6">
        <div class="col-md-6 mb-4">
          <%= render "/shared/rate_bar", number: @conversation.ratings.where( {gradee_id: @conversation.customer_id} ).first.grade %>
        </div>
      </div> 
    <% else %>
      <div class="col-md-3 mb-6">
        <% if !(current_user.customer?)  %>
          <%= render "/conversations/rating_input_form", rating: Rating.new(gradee_id: @conversation.customer_id, grader_id: @conversation.company_representative_id, conversation_id: @conversation.id) %>
        <% end %>
      </div>
    <% end %>
  </p>
<% end %>

<p>
  <strong>Status:</strong>
  <%= @conversation.status.capitalize %>
  
  <% if !(current_user.customer?) %>
    <tr>
      <div class="row mb-3">
        <div class="col-md-3">
          <div class="card" >
            <div class="card-body" >
              <%= render '/conversations/status_change_form', conversation: @conversation %>
            </div>
          </div>
        </div>
      </div>
    </tr>
  <% end %>

</p>

  <tr>
    <div id="comments_catch">
      <% @conversation.comments.order({ :created_at => :asc }).each do |a_comment| %>
          <%= render "shared/comment", comment: a_comment %>
      <% end %>
    </div>
  </tr>

<%= turbo_frame_tag "new_comment", src: new_comment_path(:a_conversation_id => params[:id]), target: "_top" %>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>