config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root "users#show"
  resources :conversations
  resources :comments
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :ratings
  #get "/ratings" => "ratings#index"
  #post "/ratings" => "ratings#create", :as => 'ratings'
  #resources :users, only: :show
  get "/:username" => "users#show"
  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_cdn_assets.html.erb
<!-- Expand the number of characters we can use in the document beyond basic ASCII 🎉 -->
<meta charset="utf-8">

<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>

app/views/shared/_conversation_navigator.html.erb
<div class="row mb-1">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"> Conversation # <%= conversation.id %></h5>
        <p class="card-text"> The status of this conversation is <%= conversation.status %> </p>
        <%= link_to "Access conversation details", conversation, class: "card-link" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="alert alert-<%= css_class %> alert-dismissible fade show" role="alert">
    <%= message %>

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">

  <div class="container">

    <%= link_to "Industrial Chat", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Home", root_path, class: "dropdown-item" %>
            <%= link_to "Ratings", ratings_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
        
          <li class="nav-item">
            <%= link_to "Edit #{current_user.username.capitalize() }", edit_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_rate_bar.html.erb
  <div class="progress">
    <div class="progress-bar" role="progressbar" style="width: <%= "#{number*20}%" %>;" aria-valuenow="1" aria-valuemin="0" aria-valuemax="5"> </div>
  </div>